# .github/recent-activity.config.yml

user: Deghim
commit_messages:
  update: "Update recent activity"
events:
  - PushEvent
  - CreateEvent
  - ForkEvent
  - IssuesEvent
  - IssueCommentEvent
  - PullRequestEvent
  - PullRequestReviewCommentEvent
  - WatchEvent
  - ReleaseEvent
  - MemberEvent
  - GollumEvent
exclude:
  repos:
    - some-old-repo
